import {test,expect} from './fixture';
import {mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import sharp from 'sharp';

test('custom sewing outlines, connections and uploaded prints save, regenerate and export',async({studio})=>{
  test.setTimeout(240000);const page=studio.page;
  await studio.login();await page.getByRole('button',{name:'Start a custom',exact:true}).click();
  const canvas=page.locator('.demo-shape-stage canvas');await expect(canvas).toBeVisible({timeout:90000});
  const project=(await studio.call('GET','/projects')).projects[0],path=`/projects/${project.id}`;
  const before=await studio.call('GET',path);expect(before.draft.document.garment.family).toBe('custom');
  await page.getByRole('button',{name:'Add piece',exact:true}).click();
  await page.getByLabel('Piece name',{exact:true}).fill('My asymmetric panel');
  await page.getByLabel('Point X (mm)',{exact:true}).fill('-43');
  await page.getByRole('button',{name:'Add point after selected',exact:true}).click();
  await expect(page.getByRole('button',{name:'Outline point 5',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Outline point 2',exact:true}).focus();await page.keyboard.press('ArrowDown');
  await page.getByText('Connect edges · 4 seams',{exact:true}).click();
  await page.getByRole('button',{name:'Remove seam side_1',exact:true}).click();
  await page.getByLabel('Edge A',{exact:true}).selectOption('front_left:1');await page.getByLabel('Edge B',{exact:true}).selectOption('front_right:3');
  await page.getByRole('button',{name:'Connect edges',exact:true}).click();
  await page.getByLabel('Fabric print',{exact:true}).selectOption('checks');
  await page.getByLabel('Print color',{exact:true}).fill('#254eba');
  await page.getByLabel('Print repeat size',{exact:true}).fill('85');await page.getByLabel('Print rotation',{exact:true}).fill('30');
  await expect.poll(async()=>(await studio.call('GET',path)).draft.document.garment.appearance?.print?.kind).toBe('checks');
  const checks=await canvas.screenshot();
  await page.getByLabel('Fabric print',{exact:true}).selectOption('image');
  const artwork=await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100"><rect width="200" height="100" fill="#e5b94f"/><path d="M-30 0L70 100M30 0L130 100M90 0L190 100M150 0L250 100" stroke="#923955" stroke-width="22"/><circle cx="100" cy="50" r="22" fill="#294f92"/></svg>')).png().toBuffer();
  await page.getByLabel('Upload fabric artwork',{exact:true}).setInputFiles({name:'my-print.png',mimeType:'image/png',buffer:artwork});
  await expect.poll(async()=>(await studio.call('GET',path)).draft.document.garment.appearance?.print?.assetId).toBeTruthy();
  await expect(page.getByText('Replace artwork',{exact:true})).toBeVisible();
  await expect.poll(async()=>(await canvas.screenshot()).equals(checks)).toBe(false);
  await page.getByRole('button',{name:'Update garment',exact:true}).click();
  await expect.poll(async()=>(await studio.call('GET',path)).project.headRevisionId).not.toBe(before.project.headRevisionId);
  let state=await studio.call('GET',path);
  await expect.poll(async()=>(await studio.call('GET',`${path}/three-d/latest?revisionId=${state.project.headRevisionId}`))?.status,{timeout:90000}).toBe('succeeded');
  const geometry=await studio.call('GET',`${path}/geometry/${state.project.headRevisionId}`),design=state.draft.document.garment.design;
  expect(geometry.panels).toHaveLength(5);expect(geometry.drafting.assembly).toHaveLength(4);
  const custom=design.pieces.find((piece:any)=>piece.name==='My asymmetric panel');expect(geometry.panels.find((piece:any)=>piece.id===custom.id).points).toEqual([...custom.points,custom.points[0]]);
  const hidden=await studio.call('POST',`${path}/exports`,{revisionId:state.project.headRevisionId,disclosure:{includeBody:false,includeReferences:false,includePatterns:false}});
  const hiddenManifest=await studio.call('GET',hidden.files.find((file:any)=>file.filename==='manifest.json').url.replace(/^\/api/,''));
  expect(hiddenManifest.sections.overview.garment.design).toBeNull();expect(hiddenManifest.sections.overview.garment.appearance.print.assetId).toBeNull();expect(hidden.files.some((file:any)=>file.mime==='image/png')).toBe(false);
  const exported=await studio.call('POST',`${path}/exports`,{revisionId:state.project.headRevisionId,disclosure:{includeBody:false,includeReferences:true,includePatterns:true}});
  const manifest=await studio.call('GET',exported.files.find((file:any)=>file.filename==='manifest.json').url.replace(/^\/api/,''));
  expect(manifest.sections.overview.garment.design).toEqual(design);expect(manifest.sections.overview.garment.appearance).toEqual(state.draft.document.garment.appearance);expect(exported.files.some((file:any)=>file.mime==='image/png')).toBe(true);
  await page.reload();await page.getByRole('button',{name:new RegExp(project.title)}).click();await expect(canvas).toBeVisible();
  await page.getByLabel('Edit pattern piece',{exact:true}).selectOption(custom.id);await expect(page.getByLabel('Piece name',{exact:true})).toHaveValue('My asymmetric panel');await expect(page.getByLabel('Fabric print',{exact:true})).toHaveValue('image');
  const directory=resolve(import.meta.dirname,'../../docs/verification/fabric-appearance');await mkdir(directory,{recursive:true});await page.screenshot({path:resolve(directory,'custom-pattern-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);await page.screenshot({path:resolve(directory,'custom-pattern-mobile.png'),fullPage:true});
});
