import { test,expect } from './fixture';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

test('description to reviewed proposal to real geometry and export survives the cookie-stripping proxy',async({studio})=>{
  const {page}=studio;
  await studio.login();
  await page.getByRole('button',{name:'New garment',exact:true}).click();
  await page.getByLabel('Garment name',{exact:true}).fill('Blue linen top');
  await page.getByLabel('Your idea',{exact:true}).fill('A blue linen sleeveless top with contrast embroidery.');
  await page.getByRole('button',{name:'Create garment'}).click();
  await page.getByRole('button',{name:'Save & generate',exact:true}).click();
  await expect(page.getByText(/Pattern generation failed:/)).toBeVisible();
  await page.getByRole('tab',{name:'Design',exact:true}).click();
  await page.getByLabel('Send these inputs to the design model').check();
  await page.getByRole('button',{name:'Interpret my design',exact:true}).click();
  await expect(page.getByRole('button',{name:'Accept design & set measurements'})).toBeEnabled();
  await expect(page.locator('.proposal-requirements')).toContainText('unsupported');
  const evidence=resolve(import.meta.dirname,'../../docs/verification/ai-prototype');
  await mkdir(evidence,{recursive:true});
  await page.screenshot({path:resolve(evidence,'proposal-desktop.png')});
  await page.getByRole('button',{name:'Accept design & set measurements'}).click();
  await expect(page.getByRole('heading',{name:'Make it your size.'})).toBeVisible();
  await expect(page.getByText(/Pattern generation failed:/)).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Interpret my design',exact:true})).not.toBeVisible();
  await page.reload();
  await page.getByRole('button',{name:/Blue linen top Updated/}).click();
  await expect(page.getByRole('heading',{name:'Make it your size.'})).toBeVisible();
  await expect(page.getByText(/Pattern generation failed:/)).toHaveCount(0);
  await expect(page.getByLabel('Height value',{exact:true})).toBeVisible();
  await page.getByLabel('Height unit',{exact:true}).selectOption('cm');
  await page.getByLabel('Height value',{exact:true}).fill('170');
  await page.screenshot({path:resolve(evidence,'measurements-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByLabel('Height value',{exact:true})).toBeInViewport();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:resolve(evidence,'measurements-mobile.png')});
  await page.setViewportSize({width:1440,height:900});
  await page.getByText('Garment shape & fit settings',{exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Geometry family'})).toHaveValue('shirt');
  await page.getByText('Try an explicitly synthetic example',{exact:true}).click();
  await page.getByRole('button',{name:'Use these assumed values'}).click();
  await expect(page.getByLabel('Garment length value',{exact:true})).toHaveValue('600');
  await page.getByRole('button',{name:'Save & generate',exact:true}).click();
  await expect(page.locator('.pattern-stage g[role="button"]')).toHaveCount(4,{timeout:30000});
  await page.getByRole('button',{name:'Save & generate',exact:true}).click();
  await expect(page.getByRole('button',{name:'Save & generate',exact:true})).toBeEnabled({timeout:30000});
  await expect(page.locator('.alert.error')).toHaveCount(0);
  const {projects}=await studio.call('GET','/projects');
  const state=await studio.call('GET',`/projects/${projects[0].id}`);
  expect(state.draft.document.interpretation.model).toBe('browser-fixture');
  expect(state.draft.document.bom[0].name).toBe('Blue linen');
  const result=await studio.call('POST',`/projects/${projects[0].id}/exports`,{revisionId:state.project.headRevisionId,disclosure:{includeBody:false,includeReferences:false,includePatterns:true}});
  expect(result.files.map((file:any)=>file.filename)).toContain('tech-pack.pdf');
  expect(result.files.some((file:any)=>/^pattern-.+\.pdf$/.test(file.filename))).toBe(true);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:resolve(evidence,'pattern-mobile.png')});
});

test('editing during a delayed interpretation keeps local work and disables stale acceptance',async({studio})=>{
  const {page}=studio;
  await studio.login();
  await page.getByRole('button',{name:'New garment',exact:true}).click();
  await page.getByLabel('Garment name',{exact:true}).fill('Original idea');
  await page.getByLabel('Your idea',{exact:true}).fill('A blue top');
  await page.getByRole('button',{name:'Create garment'}).click();
  let finish!:()=>void;
  const hold=new Promise<void>(resolve=>{finish=resolve;});
  let started!:()=>void;
  const requestStarted=new Promise<void>(resolve=>{started=resolve;});
  await page.route('**/proposals',async route=>{const response=await route.fetch();started();await hold;await route.fulfill({response});});
  await page.getByLabel('Send these inputs to the design model').check();
  await page.getByRole('button',{name:'Interpret my design',exact:true}).click();
  await requestStarted;
  await page.getByRole('textbox',{name:'The idea',exact:true}).fill('My newer asymmetric idea');
  finish();
  await expect(page.getByRole('button',{name:'Accept design & set measurements'})).toBeDisabled();
  await expect(page.getByRole('textbox',{name:'The idea',exact:true})).toHaveValue('My newer asymmetric idea');
  await expect(page.locator('.header-center small')).toHaveText('Saved');
  await page.reload();
  await page.getByRole('button',{name:/Original idea/}).click();
  await expect(page.getByRole('button',{name:'Accept design & set measurements'})).toBeDisabled();
});

test('editing while accepting retains both the newer brief and the accepted design',async({studio})=>{
  const {page}=studio;
  await studio.login();
  await page.getByRole('button',{name:'New garment',exact:true}).click();
  await page.getByLabel('Garment name',{exact:true}).fill('Acceptance race');
  await page.getByLabel('Your idea',{exact:true}).fill('A blue linen top');
  await page.getByRole('button',{name:'Create garment'}).click();
  await page.getByLabel('Send these inputs to the design model').check();
  await page.getByRole('button',{name:'Interpret my design',exact:true}).click();
  await expect(page.getByRole('button',{name:'Accept design & set measurements'})).toBeEnabled();
  let release!:()=>void,started!:()=>void;
  const paused=new Promise<void>(resolve=>{release=resolve;}),requested=new Promise<void>(resolve=>{started=resolve;});
  await page.route('**/proposals/*/accept',async route=>{const response=await route.fetch();started();await paused;await route.fulfill({response});});
  await page.getByRole('button',{name:'Accept design & set measurements'}).click();
  await requested;
  await page.getByRole('textbox',{name:'The idea',exact:true}).fill('Keep this new finishing note');
  release();
  await expect(page.getByRole('heading',{name:'Make it your size.'})).toBeVisible();
  await page.getByText('Garment shape & fit settings',{exact:true}).click();
  await expect(page.getByRole('combobox',{name:'Geometry family'})).toHaveValue('shirt');
  await expect.poll(async()=>{const {projects}=await studio.call('GET','/projects');const state=await studio.call('GET',`/projects/${projects[0].id}`);return {brief:state.draft.document.brief,family:state.draft.document.garment.family,bom:state.draft.document.bom.length};}).toEqual({brief:'Keep this new finishing note',family:'shirt',bom:1});
});
