import { test, expect } from './fixture';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { bodyFields } from '../../packages/contracts/sizing';

test('visual sizing preserves inputs, units, estimates and private reusable measurements', async ({ studio }) => {
  const { page } = studio;
  await studio.login();
  await page.getByRole('button', { name: 'New garment', exact: true }).click();
  await page.getByLabel('Garment name', { exact: true }).fill('Sizing study');
  await page.getByRole('button', { name: 'Create garment' }).click();
  await page.getByRole('button', { name: 'Customize', exact: true }).click();
  await page.getByRole('combobox', { name: 'Geometry family' }).selectOption('shirt');
  await page.getByRole('button', { name: 'Apply sample M', exact: true }).click();
  await expect(page.getByLabel('Height value', { exact: true })).toHaveValue('170');
  const originalShape = await page.locator('.body-outline path').getAttribute('d');
  await page.getByLabel('Waist slider', { exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByLabel('Waist value', { exact: true })).toHaveValue('76.1');
  expect(await page.locator('.body-outline path').getAttribute('d')).not.toBe(originalShape);
  await expect(page.getByRole('img', { name: /Approximate body diagram highlighting waist/ })).toBeVisible();
  await page.getByRole('button', { name: 'Confirm measured height', exact: true }).click();
  await page.getByRole('combobox', { name: 'Sample size' }).selectOption('3');
  await page.getByRole('button', { name: 'Apply sample L', exact: true }).click();
  await expect(page.getByLabel('Height value', { exact: true })).toHaveValue('170');
  await expect(page.getByLabel('Bust value', { exact: true })).toHaveValue('102');
  await page.getByRole('button', { name: 'Inches', exact: true }).click();
  for (const field of bodyFields) for (const endpoint of ['Home', 'End']) {
    const slider = page.getByLabel(`${field.label} slider`, { exact: true });
    await slider.focus(); await page.keyboard.press(endpoint);
    await expect(slider).toBeEnabled();
    await expect(slider).toHaveValue(String(endpoint === 'Home' ? field.min : field.max));
  }
  await page.getByRole('button', { name: 'cm', exact: true }).click();
  await page.getByLabel('Height value', { exact: true }).fill('170');
  await page.getByRole('combobox', { name: 'Sample size' }).selectOption('2');
  await page.getByRole('button', { name: 'Apply sample M', exact: true }).click();
  await page.getByLabel('Shoulder value', { exact: true }).fill('65');
  await expect(page.getByText(/Outside this engine’s/)).toBeVisible();
  await expect(page.getByLabel('Shoulder value', { exact: true })).toHaveValue('65');
  await page.getByLabel('Shoulder value', { exact: true }).fill('40');
  await page.getByText('My saved measurements', { exact: true }).click();
  await page.getByRole('button', { name: 'Save current measurements', exact: true }).click();
  await expect(page.getByText('Measurements saved privately for reuse.')).toBeVisible();
  const saved = await studio.call('GET', '/body-profile');
  expect(saved.body.bust.state).toBe('assumed');
  expect(saved.body.height.state).toBe('known');
  await page.getByLabel('Height value', { exact: true }).fill('180');
  await page.getByRole('button', { name: 'Review saved measurements', exact: true }).click();
  await expect(page.getByLabel('Height value', { exact: true })).toHaveValue('180');
  await page.getByRole('button', { name: 'Replace this draft’s body measurements', exact: true }).click();
  await expect(page.getByLabel('Height value', { exact: true })).toHaveValue('170');
  const before = await studio.call('GET', '/body-profile');
  await page.getByRole('button', { name: 'Inches', exact: true }).click();
  await page.getByRole('button', { name: 'cm', exact: true }).click();
  await page.getByRole('button', { name: 'Replace saved measurements with current values', exact: true }).click();
  await expect.poll(async () => (await studio.call('GET', '/body-profile')).version).toBe(before.version + 1);
  expect((await studio.call('GET', '/body-profile')).body).toEqual(before.body);
  await page.getByText('My saved measurements', { exact: true }).click();
  const evidence = resolve(import.meta.dirname, '../../docs/verification/sizing');
  await mkdir(evidence, { recursive: true });
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: resolve(evidence, 'desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.locator('.body-diagram').scrollIntoViewIfNeeded();await expect(page.locator('.body-diagram')).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: resolve(evidence, 'mobile.png') });
  await page.setViewportSize({ width: 320, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
