import { test,expect } from './fixture';
import { shirtDocument } from '../../packages/test-fixtures/shirt';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const evidence=resolve(import.meta.dirname,'../../docs/verification/studio-e2e');

test('description to garment, edit, source selection, reload and revision-matched export',async({studio})=>{
  test.setTimeout(180000);
  const page=studio.page;let demoRequests=0;page.on('request',request=>{if(request.url().includes('/demo-fixtures/'))demoRequests++;});
  await studio.login();
  await page.getByRole('button',{name:'New garment',exact:true}).click();
  await page.getByLabel('Garment name',{exact:true}).fill('The everyday shirt');
  await page.getByLabel('Your idea',{exact:true}).fill('complete-shirt-fixture — a relaxed woven shirt with a curved hem and front frills.');
  await page.getByLabel('Use AI to turn my description into a design.').check();
  await page.getByRole('button',{name:'Create garment'}).click();
  await page.getByRole('button',{name:'Use design & preview',exact:true}).click();
  await expect(page.locator('.demo-shape-stage canvas')).toBeVisible({timeout:90000});
  const projects=await studio.call('GET','/projects'),path=`/projects/${projects.projects[0].id}`;
  const initial=await studio.call('GET',path),first=await studio.call('GET',`${path}/three-d/latest?revisionId=${initial.project.headRevisionId}`);
  expect(first.status).toBe('succeeded');expect(first.result.shape.classification).toBe('guided-shape-approximation');
  const original=await studio.call('GET',`${path}/geometry/${initial.project.headRevisionId}`);
  await page.getByText('Find a pattern piece',{exact:true}).click();
  await page.getByLabel('Source pattern piece',{exact:true}).selectOption('sleeve_left');
  await page.getByRole('tab',{name:'Pattern',exact:true}).click();
  const panel=original.panels.find((panel:any)=>panel.id==='sleeve_left');
  await expect(page.getByRole('button',{name:`Select panel ${panel.name}`,exact:true})).toHaveClass(/selected/);
  await page.getByRole('tab',{name:'Garment preview',exact:true}).click();
  await page.getByLabel('Sleeves',{exact:true}).selectOption('short');
  await page.getByLabel('Frills',{exact:true}).selectOption('none');
  await expect(page.locator('.geometry-stale')).toContainText('Update garment');
  await page.getByRole('button',{name:'Update garment',exact:true}).click();
  await expect.poll(async()=>{const next=await studio.call('GET',path);return next.project.headRevisionId;}).not.toBe(initial.project.headRevisionId);
  const edited=await studio.call('GET',path);
  await expect.poll(async()=>(await studio.call('GET',`${path}/three-d/latest?revisionId=${edited.project.headRevisionId}`))?.status,{timeout:90000}).toBe('succeeded');
  const second=await studio.call('GET',`${path}/three-d/latest?revisionId=${edited.project.headRevisionId}`);
  expect(second.patternDigest).not.toBe(first.patternDigest);expect(second.result.shape.sha256).not.toBe(first.result.shape.sha256);
  await expect(page.locator('.demo-shape-stage canvas')).toBeVisible();
  await mkdir(evidence,{recursive:true});await page.screenshot({path:resolve(evidence,'desktop.png')});
  await page.getByRole('button',{name:'Download',exact:true}).click();
  const patternLink=page.getByRole('link',{name:/^pattern-.+\.json$/,exact:true});await expect(patternLink).toBeVisible();
  const url=(await patternLink.getAttribute('href'))!.replace(/^\/api/,'');const exported=await studio.call('GET',url);
  expect(exported.inputDigest).toBe(edited.revisions.find((r:any)=>r.id===edited.project.headRevisionId).digest);
  expect(exported.panels.some((p:any)=>p.id.startsWith('frill_'))).toBe(false);
  await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.reload();await page.getByRole('button',{name:/The everyday shirt/}).click();
  await expect(page.locator('.demo-shape-stage canvas')).toBeVisible();
  const persisted=await studio.call('GET',`${path}/three-d/latest?revisionId=${edited.project.headRevisionId}`);expect(persisted.id).toBe(second.id);
  await page.setViewportSize({width:390,height:844});
  const stage=await page.locator('.demo-shape-stage').boundingBox();expect(stage!.y).toBeLessThan(300);expect(stage!.y+stage!.height).toBeLessThan(700);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
  await page.screenshot({path:resolve(evidence,'mobile.png'),fullPage:true});
  expect(demoRequests).toBe(0);
  await studio.call('DELETE',path);await expect(page.locator('.demo-shape-stage canvas')).toHaveCount(0,{timeout:15000});
});

test('a device without WebGL keeps the pattern accessible and can reload its garment display',async({studio})=>{
  test.setTimeout(150000);await studio.login();
  const doc=shirtDocument();doc.garment.design={...doc.garment.design!,frill:'none'};
  const created=await studio.call('POST','/projects',{title:'No WebGL shirt'}),path=`/projects/${created.project.id}`;
  const draft=await studio.call('PUT',`${path}/draft`,{expectedVersion:created.draft.version,expectedRevisionId:null,document:{...doc,title:'No WebGL shirt'}});
  const state=await studio.call('POST',`${path}/revisions`,{expectedVersion:draft.version,expectedRevisionId:null});
  await studio.call('POST',`${path}/jobs`,{revisionId:state.project.headRevisionId,requestId:'fallback-pattern'});
  await expect.poll(async()=>(await studio.call('GET',`${path}/three-d/latest?revisionId=${state.project.headRevisionId}`))?.status,{timeout:90000}).toBe('succeeded');
  await studio.page.reload();
  await studio.page.evaluate(()=>{const original=HTMLCanvasElement.prototype.getContext;(window as any).restoreWebGL=()=>{HTMLCanvasElement.prototype.getContext=original;};HTMLCanvasElement.prototype.getContext=function(this:HTMLCanvasElement,kind:string,...args:any[]){return kind.includes('webgl')?null:(original as any).call(this,kind,...args);} as typeof original;});
  await studio.page.getByRole('button',{name:/No WebGL shirt/}).click();
  await expect(studio.page.getByRole('alert').filter({hasText:'3D rendering is unavailable'})).toBeVisible();
  await studio.page.getByText('Find a pattern piece',{exact:true}).click();await studio.page.getByLabel('Source pattern piece',{exact:true}).selectOption('front_left');
  await studio.page.evaluate(()=>(window as any).restoreWebGL());await studio.page.getByRole('button',{name:'Reload display',exact:true}).click();
  await expect(studio.page.locator('.demo-shape-stage canvas')).toBeVisible();
  await studio.page.locator('.demo-shape-stage canvas').evaluate(canvas=>canvas.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));
  await expect(studio.page.getByRole('alert').filter({hasText:'display was interrupted'})).toBeVisible();
  await studio.page.getByRole('button',{name:'Reload display',exact:true}).click();await expect(studio.page.getByRole('button',{name:'Back',exact:true})).toBeEnabled();
  await studio.page.getByRole('button',{name:'Flat pieces',exact:true}).click();await expect(studio.page.locator('.three-d-canvas canvas')).toBeVisible();
  await studio.page.getByRole('button',{name:'Mesh edges',exact:true}).click();await expect(studio.page.getByRole('button',{name:'Mesh edges',exact:true})).toHaveAttribute('aria-pressed','true');
  await studio.page.getByRole('tab',{name:'Pattern',exact:true}).click();await expect(studio.page.locator('.pattern-stage svg[role="img"]')).toBeVisible();
});
