import {useRef,useState} from 'react';
import {CustomPatternSchema,customPatternIssues,type CustomPattern,type CustomPiece} from '../../../../packages/contracts/custom-pattern';
export default function CustomPatternEditor({design,onChange}:{design:CustomPattern;onChange:(design:CustomPattern)=>void}) {
  const [selected,setSelected]=useState(design.pieces[0]!.id),[pointIndex,setPointIndex]=useState(0),[edgeA,setEdgeA]=useState(''),[edgeB,setEdgeB]=useState(''),[treatment,setTreatment]=useState<'plain'|'gather'>('plain');
  const svg=useRef<SVGSVGElement>(null),drag=useRef<number|null>(null);
  const piece=design.pieces.find(piece=>piece.id===selected)??design.pieces[0]!,point=piece.points[Math.min(pointIndex,piece.points.length-1)]!;
  const change=(next:CustomPattern)=>{const parsed=CustomPatternSchema.safeParse(next);if(parsed.success)onChange(parsed.data);};
  const update=(next:Partial<CustomPiece>)=>change({...design,pieces:design.pieces.map(p=>p.id===piece.id?{...p,...next}:p)});
  const move=(index:number,x:number,y:number)=>update({points:piece.points.map((p,i)=>i===index?[Math.max(-2000,Math.min(2000,Math.round(x))),Math.max(-2000,Math.min(2000,Math.round(y)))]:p)});
  const topology=(points:[number,number][])=>{change({...design,pieces:design.pieces.map(p=>p.id===piece.id?{...p,points}:p),seams:design.seams.filter(s=>s.a!==piece.id&&s.b!==piece.id)});setPointIndex(0);};
  const add=(copy=false)=>{const id=`piece_${crypto.randomUUID().slice(0,8)}`;change({...design,pieces:[...design.pieces,copy?{...structuredClone(piece),id,name:`${piece.name} copy`}:{id,name:`Piece ${design.pieces.length+1}`,points:[[0,0],[250,0],[250,300],[0,300]],placement:{positionMm:[0,0,250],rotationDeg:[0,0,0],bendDeg:0}}]});setSelected(id);setPointIndex(0);};
  const xs=piece.points.map(p=>p[0]),ys=piece.points.map(p=>p[1]),minX=Math.min(-50,...xs)-30,minY=Math.min(-50,...ys)-30,width=Math.max(550,...xs)-minX+30,height=Math.max(700,...ys)-minY+30;
  const edges=design.pieces.flatMap(p=>p.points.map((v,index)=>{const next=p.points[(index+1)%p.points.length]!;return {value:`${p.id}:${index}`,label:`${p.name} · edge ${index+1} · ${Math.hypot(v[0]-next[0],v[1]-next[1]).toFixed(1)} mm`};}));
  const issues=customPatternIssues(design);
  return <section className="custom-pattern-editor" aria-label="Custom sewing pattern">
    <h3>Your sewing pieces</h3><p>Drag outline points or enter exact millimetres. Add pieces and connect their edges, then choose Update garment.</p>
    <label className="field"><span>Pattern piece</span><select aria-label="Edit pattern piece" value={piece.id} onChange={event=>{setSelected(event.target.value);setPointIndex(0);}}>{design.pieces.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <div className="pattern-actions"><button type="button" disabled={design.pieces.length>=16} onClick={()=>add()}>Add piece</button><button type="button" disabled={design.pieces.length>=16} onClick={()=>add(true)}>Duplicate piece</button><button type="button" disabled={design.pieces.length===1} onClick={()=>{change({...design,pieces:design.pieces.filter(p=>p.id!==piece.id),seams:design.seams.filter(s=>s.a!==piece.id&&s.b!==piece.id)});setSelected(design.pieces.find(p=>p.id!==piece.id)!.id);setPointIndex(0);}}>Remove piece</button></div>
    <label className="field"><span>Piece name</span><input aria-label="Piece name" value={piece.name} onChange={event=>update({name:event.target.value})}/></label>
    <svg className="custom-outline" ref={svg} viewBox={`${minX} ${minY} ${width} ${height}`} aria-label="Editable sewing outline" role="group" onPointerMove={event=>{if(drag.current===null||!svg.current)return;const matrix=svg.current.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());move(drag.current,p.x,p.y);}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
      <polygon points={piece.points.map(p=>p.join(',')).join(' ')} fill="#e6ece5" stroke="#385b45" strokeWidth="3"/>
      {piece.points.map((p,index)=>{const next=piece.points[(index+1)%piece.points.length]!;return <g key={index}><text x={(p[0]+next[0])/2+8} y={(p[1]+next[1])/2-8} fontSize="18" fill="#637465">{index+1}</text><circle role="button" aria-label={`Outline point ${index+1}`} tabIndex={0} cx={p[0]} cy={p[1]} r={index===pointIndex?12:9} fill={index===pointIndex?'#cb6943':'#385b45'} onPointerDown={event=>{event.preventDefault();setPointIndex(index);drag.current=index;event.currentTarget.setPointerCapture(event.pointerId);}} onKeyDown={event=>{const delta=event.shiftKey?1:10;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();setPointIndex(index);move(index,p[0]+(event.key==='ArrowRight'?delta:event.key==='ArrowLeft'?-delta:0),p[1]+(event.key==='ArrowDown'?delta:event.key==='ArrowUp'?-delta:0));}}} onFocus={()=>setPointIndex(index)}/></g>;})}
    </svg>
    <div className="two-fields"><label className="field"><span>Point {pointIndex+1} · X (mm)</span><input aria-label="Point X (mm)" type="number" min="-2000" max="2000" value={point[0]} onChange={event=>move(pointIndex,Number(event.target.value),point[1])}/></label><label className="field"><span>Y (mm)</span><input aria-label="Point Y (mm)" type="number" min="-2000" max="2000" value={point[1]} onChange={event=>move(pointIndex,point[0],Number(event.target.value))}/></label></div>
    <div className="pattern-actions"><button disabled={piece.points.length>=30} onClick={()=>{const next=piece.points[(pointIndex+1)%piece.points.length]!;const points=[...piece.points];points.splice(pointIndex+1,0,[(point[0]+next[0])/2,(point[1]+next[1])/2]);topology(points);}}>Add point after selected</button><button disabled={piece.points.length<=3} onClick={()=>topology(piece.points.filter((_,index)=>index!==pointIndex))}>Remove point</button></div>
    <small>Adding or removing points clears this piece’s seam connections. Each piece is cut once; duplicate it for another copy.</small>
    <details><summary>Place this piece in 3D</summary><p>These controls pose the preview. They do not predict drape or change the flat outline.</p>
      <label className="field"><span>Bend around · {piece.placement.bendDeg}°</span><input aria-label="Piece bend" type="range" min="-360" max="360" step="5" value={piece.placement.bendDeg} onChange={event=>update({placement:{...piece.placement,bendDeg:Number(event.target.value)}})}/></label>
      {(['X','Y','Z'] as const).map((axis,i)=><div className="two-fields" key={axis}><label className="field"><span>{axis} position (mm)</span><input aria-label={`${axis} placement`} type="number" min="-2000" max="2000" step="10" value={piece.placement.positionMm[i]} onChange={event=>{const positionMm=[...piece.placement.positionMm] as [number,number,number];positionMm[i]=Number(event.target.value);update({placement:{...piece.placement,positionMm}});}}/></label><label className="field"><span>{axis} rotation (°)</span><input aria-label={`${axis} rotation`} type="number" min="-180" max="180" step="5" value={piece.placement.rotationDeg[i]} onChange={event=>{const rotationDeg=[...piece.placement.rotationDeg] as [number,number,number];rotationDeg[i]=Number(event.target.value);update({placement:{...piece.placement,rotationDeg}});}}/></label></div>)}
    </details>
    <details><summary>Connect edges · {design.seams.length} seams</summary>
      {design.seams.map(seam=><div className="custom-seam" key={seam.id}><span>{design.pieces.find(p=>p.id===seam.a)?.name} {seam.edgeA+1} → {design.pieces.find(p=>p.id===seam.b)?.name} {seam.edgeB+1} · {seam.treatment}</span><button aria-label={`Remove seam ${seam.id}`} onClick={()=>change({...design,seams:design.seams.filter(s=>s.id!==seam.id)})}>Remove</button></div>)}
      {([['Edge A',edgeA,setEdgeA],['Edge B',edgeB,setEdgeB]] as const).map(([label,value,set])=><label className="field" key={label}><span>{label}</span><select aria-label={label} value={value} onChange={event=>set(event.target.value)}><option value="">Choose an edge</option>{edges.map(edge=><option key={edge.value} value={edge.value}>{edge.label}</option>)}</select></label>)}
      <label className="field"><span>Seam treatment</span><select aria-label="Seam treatment" value={treatment} onChange={event=>setTreatment(event.target.value as 'plain'|'gather')}><option value="plain">Plain · equal edge lengths</option><option value="gather">Gather A onto B · up to 3×</option></select></label>
      <button disabled={!edgeA||!edgeB||edgeA===edgeB||design.seams.length>=100} onClick={()=>{const [a,ae]=edgeA.split(':'),[b,be]=edgeB.split(':');change({...design,seams:[...design.seams,{id:`seam_${crypto.randomUUID().slice(0,8)}`,a:a!,edgeA:Number(ae),b:b!,edgeB:Number(be),treatment}]});setEdgeA('');setEdgeB('');}}>Connect edges</button>
    </details>
    <label className="field"><span>Seam allowance (mm)</span><input aria-label="Custom seam allowance" type="number" min="6" max="20" value={design.seamAllowanceMm} onChange={event=>change({...design,seamAllowanceMm:Number(event.target.value)})}/></label>
    {!!issues.length&&<div role="status">{issues.map(issue=><p key={issue}>{issue}</p>)}</div>}
    <small>Up to 16 pieces and 30 points per outline. Curves use outline points. Holes, darts, grading and automatic fit are not supported yet.</small>
  </section>;
}
